### ISSUE TITLE
Discussion - Database connection support MySQL plus more

### ISSUE THREAD

**Issue by 13rac1** [mrf/grush#3]
https://github.com/go-sql-driver/mysql looks like it will cover the default mysql needs. Do we want to support other DBs? Probably best to start with just this one.

But there's also:
- https://github.com/denisenkom/go-mssqldb
- https://github.com/lib/pq

**Comment by mrf** [comment]
I'm totally fine with a lone mysql dependency for now. That covers 90% of Drupal sites from my experience.
